module.exports = {
    AccountRoute: require("./account.route"),
    AdminRoute: require("./admin.route"),
    // AssignmentRoute: require("./assignment.route"),
    CategoryRoute: require("./category.route"),
    ClassRoute: require("./class.route"),
    CommentRoute: require("./comment.route"),
    CourseRoute: require("./course.route"),
    DocumentRoute: require("./document.route"),
    FeedbackRoute: require("./feedback.route"),
    // FeedbackDetailRoute: require("./feedbackdetail.route"),
    // MockingTestRoute: require("./mockingtest.route"),
    // ResponseRoute: require("./response.route"),
    ScheduleRoute: require("./schedule.route"),
    QuestionRoute: require("./question.route"),
    ShiftRoute: require("./shift.route"),
    StudentRoute: require("./student.route"),
    TeacherRoute: require("./teacher.route"),
    // SubmitRoute: require("./submit.route"),
    // TestListRoute: require("./testlist.route"),
    UserRoute: require("./user.route"),
    AbsenceRoute: require("./absence.route"),
};