module.exports = {
    Absence: require("./absence.model"),
    Admin: require("./admin.model"),
    Assignment: require("./assignment.model"),
    Category: require("./category.model"),
    Class: require("./class.model"),
    Comment: require("./comment.model"),
    Course: require("./course.model"),
    Document: require("./document.model"),
    Feedback: require("./feedback.model"),
    FeedbackDetail: require("./feedbackdetail.model"),
    MockingTest: require("./mockingtest.model"),
    Question: require("./question.model"),
    Response: require("./response.model"),
    Schedule: require("./schedule.model"),
    Shift: require("./shift.model"),
    Student: require("./student.model"),
    Teacher: require("./teacher.model"),
    Submit: require("./submit.model"),
    TestList: require("./testlist.model"),
    //User: require("./user.model"),
};